
all:

install:
	@test -d $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic || mkdir -p $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic
	cp -f uic/objcreator.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/objcreator.py
	cp -f uic/pyuic.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/pyuic.py
	cp -f uic/icon_cache.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/icon_cache.py
	cp -f uic/uiparser.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/uiparser.py
	cp -f uic/driver.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/driver.py
	cp -f uic/properties.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/properties.py
	cp -f uic/__init__.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/__init__.py
	cp -f uic/exceptions.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/exceptions.py
	cp -f uic/autoconnect.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/autoconnect.py
	@test -d $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/widget-plugins || mkdir -p $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/widget-plugins
	cp -f uic/widget-plugins/qaxcontainer.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/widget-plugins/qaxcontainer.py
	cp -f uic/widget-plugins/qtwebkit.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/widget-plugins/qtwebkit.py
	cp -f uic/widget-plugins/qwt.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/widget-plugins/qwt.py
	cp -f uic/widget-plugins/qscintilla.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/widget-plugins/qscintilla.py
	cp -f uic/widget-plugins/phonon.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/widget-plugins/phonon.py
	@test -d $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Loader || mkdir -p $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Loader
	cp -f uic/Loader/__init__.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Loader/__init__.py
	cp -f uic/Loader/loader.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Loader/loader.py
	cp -f uic/Loader/qobjectcreator.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Loader/qobjectcreator.py
	@test -d $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler || mkdir -p $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler
	cp -f uic/Compiler/proxy_type.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler/proxy_type.py
	cp -f uic/Compiler/indenter.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler/indenter.py
	cp -f uic/Compiler/compiler.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler/compiler.py
	cp -f uic/Compiler/misc.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler/misc.py
	cp -f uic/Compiler/qtproxies.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler/qtproxies.py
	cp -f uic/Compiler/proxyproperties.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler/proxyproperties.py
	cp -f uic/Compiler/__init__.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler/__init__.py
	cp -f uic/Compiler/qobjectcreator.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/Compiler/qobjectcreator.py
	@test -d $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v2 || mkdir -p $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v2
	cp -f uic/port_v2/proxy_base.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v2/proxy_base.py
	cp -f uic/port_v2/invoke.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v2/invoke.py
	cp -f uic/port_v2/load_plugin.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v2/load_plugin.py
	cp -f uic/port_v2/string_io.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v2/string_io.py
	cp -f uic/port_v2/__init__.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v2/__init__.py
	cp -f uic/port_v2/encode_utf8.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v2/encode_utf8.py
	cp -f uic/port_v2/ascii_upper.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v2/ascii_upper.py
	@test -d $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v3 || mkdir -p $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v3
	cp -f uic/port_v3/proxy_base.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v3/proxy_base.py
	cp -f uic/port_v3/invoke.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v3/invoke.py
	cp -f uic/port_v3/load_plugin.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v3/load_plugin.py
	cp -f uic/port_v3/string_io.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v3/string_io.py
	cp -f uic/port_v3/__init__.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v3/__init__.py
	cp -f uic/port_v3/encode_utf8.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v3/encode_utf8.py
	cp -f uic/port_v3/ascii_upper.py $(DESTDIR)/usr/lib/python2.5/site-packages/PyQt4/uic/port_v3/ascii_upper.py
	@test -d $(DESTDIR)/usr/bin || mkdir -p $(DESTDIR)/usr/bin
	cp -f pyuic4 $(DESTDIR)/usr/bin/pyuic4

clean:
