/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.9.1 on Wed Feb 17 09:47:37 2010
 *
 * Copyright (c) 2009 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtXml.h"

#line 420 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 39 "sipQtXmlQDomNotation.cpp"

#line 69 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 43 "sipQtXmlQDomNotation.cpp"
#line 41 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 46 "sipQtXmlQDomNotation.cpp"
#line 340 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 49 "sipQtXmlQDomNotation.cpp"
#line 41 "sip/QtCore/qtextstream.sip"
#include <qtextstream.h>
#line 52 "sipQtXmlQDomNotation.cpp"
#line 394 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 55 "sipQtXmlQDomNotation.cpp"
#line 301 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 58 "sipQtXmlQDomNotation.cpp"
#line 464 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 61 "sipQtXmlQDomNotation.cpp"
#line 435 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 64 "sipQtXmlQDomNotation.cpp"
#line 380 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 67 "sipQtXmlQDomNotation.cpp"
#line 451 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 70 "sipQtXmlQDomNotation.cpp"
#line 197 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 73 "sipQtXmlQDomNotation.cpp"
#line 216 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 76 "sipQtXmlQDomNotation.cpp"
#line 288 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 79 "sipQtXmlQDomNotation.cpp"
#line 407 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 82 "sipQtXmlQDomNotation.cpp"
#line 322 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 85 "sipQtXmlQDomNotation.cpp"
#line 261 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 88 "sipQtXmlQDomNotation.cpp"
#line 176 "sip/QtXml/qdom.sip"
#include <qdom.h>
#line 91 "sipQtXmlQDomNotation.cpp"


extern "C" {static PyObject *meth_QDomNotation_publicId(PyObject *, PyObject *);}
static PyObject *meth_QDomNotation_publicId(PyObject *sipSelf, PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        QDomNotation *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"B",&sipSelf,sipType_QDomNotation,&sipCpp))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->publicId());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipName_QDomNotation,sipName_publicId);

    return NULL;
}


extern "C" {static PyObject *meth_QDomNotation_systemId(PyObject *, PyObject *);}
static PyObject *meth_QDomNotation_systemId(PyObject *sipSelf, PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        QDomNotation *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"B",&sipSelf,sipType_QDomNotation,&sipCpp))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->systemId());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipName_QDomNotation,sipName_systemId);

    return NULL;
}


extern "C" {static PyObject *meth_QDomNotation_nodeType(PyObject *, PyObject *);}
static PyObject *meth_QDomNotation_nodeType(PyObject *sipSelf, PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        QDomNotation *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"B",&sipSelf,sipType_QDomNotation,&sipCpp))
        {
            QDomNode::NodeType sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->nodeType();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QDomNode_NodeType);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipName_QDomNotation,sipName_nodeType);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QDomNotation(void *, const sipTypeDef *);}
static void *cast_QDomNotation(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QDomNotation)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QDomNode)->ctd_cast((QDomNode *)(QDomNotation *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QDomNotation(void *, int);}
static void release_QDomNotation(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QDomNotation *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_QDomNotation(void *, SIP_SSIZE_T, const void *);}
static void assign_QDomNotation(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QDomNotation *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QDomNotation *>(sipSrc);
}


extern "C" {static void *array_QDomNotation(SIP_SSIZE_T);}
static void *array_QDomNotation(SIP_SSIZE_T sipNrElem)
{
    return new QDomNotation[sipNrElem];
}


extern "C" {static void *copy_QDomNotation(const void *, SIP_SSIZE_T);}
static void *copy_QDomNotation(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QDomNotation(reinterpret_cast<const QDomNotation *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QDomNotation(sipSimpleWrapper *);}
static void dealloc_QDomNotation(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QDomNotation(sipSelf->u.cppPtr,0);
    }
}


extern "C" {static void *init_QDomNotation(sipSimpleWrapper *, PyObject *, PyObject **, int *);}
static void *init_QDomNotation(sipSimpleWrapper *, PyObject *sipArgs, PyObject **, int *sipArgsParsed)
{
    QDomNotation *sipCpp = 0;

    if (!sipCpp)
    {
        if (sipParseArgs(sipArgsParsed,sipArgs,""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QDomNotation();
            Py_END_ALLOW_THREADS
        }
    }

    if (!sipCpp)
    {
        const QDomNotation * a0;

        if (sipParseArgs(sipArgsParsed,sipArgs,"J9",sipType_QDomNotation,&a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QDomNotation(*a0);
            Py_END_ALLOW_THREADS
        }
    }

    return sipCpp;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QDomNotation[] = {{13, 255, 1}};


static PyMethodDef methods_QDomNotation[] = {
    {SIP_MLNAME_CAST(sipName_nodeType), meth_QDomNotation_nodeType, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_publicId), meth_QDomNotation_publicId, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_systemId), meth_QDomNotation_systemId, METH_VARARGS, NULL}
};


pyqt4ClassTypeDef sipTypeDef_QtXml_QDomNotation = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QDomNotation,
        {0}
    },
    {
        sipNameNr_QDomNotation,
        {0, 0, 1},
        3, methods_QDomNotation,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    -1,
    -1,
    supers_QDomNotation,
    0,
    init_QDomNotation,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QDomNotation,
    assign_QDomNotation,
    array_QDomNotation,
    copy_QDomNotation,
    release_QDomNotation,
    cast_QDomNotation,
    0,
    0,
    0
},
    0,
    0,
    0
};
